[project]
name = "robotframework-project-template"
version = "0.1.0"
description = ""
authors = [
    {name = "Kelby Stine",email = "kelbystine@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12,<3.14"
package-mode = false

[tool.poetry.group.test.dependencies]
robotframework = "^7.2.0"
robotframework-requests = "^0.9.7"
robotframework-seleniumlibrary = "^6.7.0"
robotframework-jsonlibrary = "^0.5"

[tool.poetry.group.dev.dependencies]
robotframework-tidy = "^4.16.0"
robotframework-robocop = "^5.8.1"
robotcode-runner = "^0.108.0"

[tool.poetry.dependencies]
[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
