[tool.robocop.lint]
ignore = [
    "VAR05",
    "VAR06",
]

[tool.robocop.format]
diff = true
overwrite = true
configure = [
    "AlignSettingsSection.up_to_column=2",
    "AlignVariablesSection.up_to_column=3",
    "DiscardEmptySections.allow_only_comments=True",
    "NormalizeAssignments.equal_sign_type=remove",
    "NormalizeNewLines.section_lines=2",
    "NormalizeNewLines.test_case_lines=1",
    "NormalizeNewLines.keyword_lines=1",
    "NormalizeNewLines.consecutive_lines=0",
    "NormalizeNewLines.separate_templated_tests=True",
    "NormalizeSectionHeaderName.uppercase=false",
    "OrderSettingsSection.group_order=documentation,imports,tags,settings",
    "OrderSettingsSection.new_lines_between_groups=2",
    "SplitTooLongLine.split_on_every_arg=false",
    "SplitTooLongLine.line_length=120",
]

[project]
name = "robotframework-project-template"
version = "0.1.0"
description = ""
authors = [
    {name = "Kelby Stine",email = "kelbystine@gmail.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12,<3.14"
package-mode = false

[tool.poetry.group.test.dependencies]
robotframework = "^7.2.0"
robotframework-requests = "^0.9.7"
robotframework-seleniumlibrary = "^6.7.0"
robotframework-jsonlibrary = "^0.5"

[tool.poetry.group.dev.dependencies]
robotframework-tidy = "^4.16.0"
robotframework-robocop = "^5.8.1"
robotcode-runner = "^0.108.0"

[tool.poetry.dependencies]
[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
