extend-python-path = [".", "Resources", "CustomLibraries"]
default_profiles = "common"

[profiles.common]
output-dir = "Results"
xunit = "junit.xml"

[profiles.local]
inherits = "common"
args = ["-A", "Data/ArgumentsFiles/Local/Arguments.robot"]
paths = ["Tests"]

[profiles.run-all]
inherits = "common"
paths = ["Tests"]

[profiles.dryrun-all]
inherits = "run-all"
dry-run = true

[profiles.browser]
inherits = "common"
suites = ["BrowserTest"]
paths = ["Tests"]

[profiles.requests]
inherits = "common"
suites = ["RequestsTest"]
paths = ["Tests"]