SELENIUM_STRATEGY: local
WEB_BROWSER: chrome  # chromium, firefox, webkit
BROWSER_IS_HEADLESS: true
USER_DATA_DIR: Results/UserData
CHROME_EXECUTABLE_PATH: null  # Or comment out to use webdriver-manager auto-detection
SELENIUM_CONFIGURATION:
  SPEED: 0
  TIMEOUT: 60
REMOTE_WEBDRIVER_CONFIGURATION:
  URL: http://localhost:4444
  URI: /wd/hub
DOCKER_COMPOSE_CONFIGURATION:
  URL: http://selenium-chrome-server:4444
  OVERVIEW: /ui
  SESSION: /ui/#/sessions
  HELP: /ui/#/help
  VNC_SERVER: http://localhost:7900/?autoconnect=1&resize=scale&password=secret
  HOST_VOLUME: /Downloads
DEFAULT_WINDOW_RESOLUTION: FHD
DISPLAY_RESOLUTION_DICT:
  MAX:
    WIDTH: 0
    HEIGHT: 0
    ASPECT: null
  VGA:
    WIDTH: 640
    HEIGHT: 480
    ASPECT: 4:3
  SVGA:
    WIDTH: 800
    HEIGHT: 600
    ASPECT: 4:3
  XGA:
    WIDTH: 1024
    HEIGHT: 768
    ASPECT: 4:3
  TT_HIGH_RESOLUTION:
    WIDTH: 1280
    HEIGHT: 960
    ASPECT: 4:3
  SXGA+:
    WIDTH: 1400
    HEIGHT: 1050
    ASPECT: 4:3
  UXGA:
    WIDTH: 1600
    HEIGHT: 1200
    ASPECT: 4:3
  HI_RES_CRT:
    WIDTH: 1920
    HEIGHT: 1440
    ASPECT: 4:3
  QXGA:
    WIDTH: 2048
    HEIGHT: 1536
    ASPECT: 4:3
  WXGA:
    WIDTH: 1280
    HEIGHT: 800
    ASPECT: 16:10
  WXGA+:
    WIDTH: 1440
    HEIGHT: 900
    ASPECT: 16:10
  WSXGA+:
    WIDTH: 1680
    HEIGHT: 1050
    ASPECT: 16:10
  WUXGA:
    WIDTH: 1920
    HEIGHT: 1200
    ASPECT: 16:10
  WQXGA:
    WIDTH: 2560
    HEIGHT: 1600
    ASPECT: 16:10
  HD1:
    WIDTH: 1280
    HEIGHT: 720
    ASPECT: 16:9
  HD+:
    WIDTH: 1600
    HEIGHT: 900
    ASPECT: 16:9
  FHD:
    WIDTH: 1920
    HEIGHT: 1080
    ASPECT: 16:9
  QHD:
    WIDTH: 2560
    HEIGHT: 1440
    ASPECT: 16:9
  UHD_4K:
    WIDTH: 3840
    HEIGHT: 2160
    ASPECT: 16:9
